[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hcie"
version = "0.1.0"
description = "Heterocycle Isostere Explorer"
requires-python = ">=3.10"
license = "MIT"
dependencies = ["numpy", "rdkit", "scipy"]

[tool.setuptools.packages.find]
where = ["."]
include = ["hcie*", "Data*"]

[tool.setuptools.package-data]
Data = ["*.json"]
